import React from 'react'
import { whatIs } from '../../content'
import SectionWrapper from '../ui/SectionWrapper'
import SectionLabel from '../ui/SectionLabel'
import DebugLabel from '../ui/DebugLabel'

export default function WhatIsSectionCopy({ debugMode = false }) {
  return (
    <SectionWrapper id="was-ist-copy" data-testid="whatis-section-copy">
      {/* Hidden: ensures text-color-accent CSS is generated by Tailwind JIT */}
      <span className="hidden text-color-accent" aria-hidden="true"></span>
      <div className="grid md:grid-cols-2 grid-gap-xl items-start">
        {/* Left — sticky headline */}
        <div className="md:sticky md:top-32">
          <DebugLabel type="typography-label" debugMode={debugMode}>
            <SectionLabel text={whatIs.label} />
          </DebugLabel>
          <DebugLabel type="typography-hero" debugMode={debugMode}>
            <h2 className="font-secondary text-hero text-color-primary leading-tight">
              {whatIs.headline}
            </h2>
          </DebugLabel>
        </div>

        {/* Right — body + skeptic toggle */}
        <div>
          {whatIs.body.map((para, i) => (
            <DebugLabel type="typography-body" debugMode={debugMode} key={i}>
              <p className={`font-primary text-color-text text-body ${i > 0 ? 'margin-top-sm' : ''}`}>
                {para}
              </p>
            </DebugLabel>
          ))}
        </div>
      </div>
    </SectionWrapper>
  )
}
